### ISSUE TITLE
Are you using the default semantic-ui-css package/theme? How to Customize?

### ISSUE THREAD

**Issue by gotjoshua** [factoryThings/fTboilerplate#2]
In npm ls, I see:
semantic-ui-css@2.3.2
Does this deserve a place in the readme list?

How can one customize or use different themes?

**Comment by gotjoshua** [comment]
There seem to be many options:
https://www.npmjs.com/package/semantic-ui#additional-versions

How did you decide which one to use? would i need to uninstall the semantic-ui-css@2.3.2 in order to use another one?

**Comment by jfhenon** [comment]
For simplicity, the boilerplate uses the default theme but you can indeed switch to your own theme. See https://semantic-ui.com/usage/theming.html
